name: Ktlint CI

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]

  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check code style
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin --warning-mode all --stacktrace
